### ISSUE TITLE
How to correctly set the "total" value without loading everything

### ISSUE THREAD

**Issue by Bazze** [felixheck/bissle#1]
How would one go about setting the `total` attribute to a "correct" value? From what I can see in the source code now it just checks the length of the result array, but I wouldn't want to load all rows from the database if I'm just interested in the first X rows. I would probably want to execute a count query (or similar) on the side and then set the `total` to that value. Is there any easy way to override the `total` value?

**Comment by felixheck** [comment]
Hey @Bazze — currently it's not supported.
But I could provide a `total` option, which could replaces the internal value and stops splicing the result array. Is that an option for you?

**Comment by felixheck** [comment]
v0.7.0 is now released. There is a [new option](https://github.com/felixheck/bissle#replybissleresponse-options) called `total`. As soon as you pass a number (e.g. you total count generated by a count query), the internally generated `total` value gets overwritten and the passed data don't get spliced anymore.

So you are able to request just the first X rows from the database and the total count.  
Hope it helps. If not, feel free to let me know: hi@whotheheck.de

**Comment by Bazze** [comment]
Great, thanks! This should solve the problem :)
