### ISSUE TITLE
Changing the parameter names

### ISSUE THREAD

**Issue by Bazze** [felixheck/bissle#2]
Hello!

I want to keep my query parameters in camelCase, so I need to change the default `per_page` query parameter. I can see that there is no such support right now, but I'll be happy to contribute. Would it be a welcomed contribution?

I was thinking to introduce a new plugin option, something like this:
```javascript
{
  pluginOptions: {
    absolute: Joi.boolean().default(false),
    paramNames: Joi
      .object({
        per_page: Joi.string().default('per_page'),
        page: Joi.string().default('page'),
        total: Joi.string().default('total'),
      })
      .default({
        per_page: 'per_page',
        page: 'page',
        total: 'total',
      }),
}
```

Do you have any preference on how to implement it?

**Comment by felixheck** [comment]
I'll check it the next days but looks useful up to now :)

**Comment by felixheck** [comment]
@Bazze v1.0.0 is just released!
Thanks for your contribution :)

**Comment by Bazze** [comment]
Sweet, thanks for that @felixheck. Just one small thing, a `console.log` statement slipped through in the release: https://github.com/felixheck/bissle/blob/master/src/index.js#L57

**Comment by felixheck** [comment]
Nooo.. :D
v1.0.1 will be released in a few seconds!

edit: @Bazze just released! Thanks again!
