### ISSUE TITLE
Passing params to pagination links

### ISSUE THREAD

**Issue by johannessjoberg** [felixheck/bissle#5]
Currently when having a when have a route with a param for example: `/resource/{id}/subResource` akaya throws an error, 'The id parameter is missing', for the pagination links. This is because the `getPaginationLink` method does not pass params to akaya.

I'd suggest updating the `getPaginationLink` to pass along request.params to fix this. For example:
```
function getPaginationLink(id, per_page, options, request, aka, absolute) {
  per_page = minimizeQueryParameter(per_page, options.per_page);

  return function (page) {
    page = minimizeQueryParameter(page, 1);

    return aka(id, {
      query: Object.assign({}, request.query, { page: page, per_page: per_page }),
      params: request.params
    }, {
      rel: !absolute
    });
  };
}
```

Do you want me to supply a pull request?

**Comment by felixheck** [comment]
@johannessjoberg Thanks for contributing!

Yes, a PR would be great!
Just change the few lines, add a simple unit test and set a ref between PR & Issue.  Gonna merge it ASAP 😊

Thanks!

**Comment by felixheck** [comment]
@Bazze & @johannessjoberg:

I've updated lots of dev dependencies:
- replaced eslint with standard
- removed babel --> full es6-compliant

Update to `v1.2.2` :)

**Comment by Bazze** [comment]
Awesome! Thanks a bunch @felixheck. We should get a `.editorconfig` file in place too 😍

**Comment by felixheck** [comment]
@Bazze suggestions? ;-) PR? :)

Quite busy updating my other hapi plugins :D

**Comment by Bazze** [comment]
When you least expect it, a PR shall arrive!
