### ISSUE TITLE
Conditional response based on Accept header

### ISSUE THREAD

**Issue by flasaracina** [felixheck/bissle#60]
Hello!
is it possible to have bissle return the HATEOASified response only if the Accept header is `application/hal+json` ?

Thank you

**Comment by felixheck** [comment]
Hiya  — sure, in theory, it's possible. It's not implemented yet though.
What would you expect in case of `application/json`? Just the paginated payload?

**Comment by flasaracina** [comment]
@felixheck 
I would expect a non paginated resultset. It would be a developer responsibility to conform to parameters that dictate pagination. I am advocating this just because HATEOAS in general is useful in a browser based context, but it will become cumbersome quickly in a non browser environment.

I'd like to have the choice to have the resulset decorated with the HATEOAS metadata. Halacious does this by giving us the option to choose for which "media types" we want the response decorated with HATEOAS metadata (see this link for reference: [options: mediaTypes](https://github.com/bleupen/halacious#plugin-options) ). Your plugin is compatible with the halacious one so I thought it would make sense to adopt this policy also for the paginated resulset your plugin is giving us.

Thanks
