### ISSUE TITLE
Add Support for Hapi v17

### ISSUE THREAD

**Issue by felixheck** [felixheck/bissle#8]
- [x] remove `tail`
- [x] support `async`/`await`
- [x] remove multiple connections
- [x] update dependencies (node, npm & hapi)
- [x] update documentation
- [x]  update examples

**Comment by johannessjoberg** [comment]
Hello! Currently updating to Hapi 17 and saw that the documentation still mentions `reply` in `reply.bissle(response, [options])` section. Should be a correction. Thanks for a great plugin!

**Comment by felixheck** [comment]
Hi 👋 Glad you still use the plugin, Johannes!

It's `h.bissle()` instead, right?

**Comment by felixheck** [comment]
updated, thanks a lot for reporting! 🙏

**Comment by johannessjoberg** [comment]
Wow, that was fast! Nicely done! 👍

**Comment by felixheck** [comment]
my modules are my babies 😊

**Comment by johannessjoberg** [comment]
😍
